version: "3.8"

services:
  trino-coordinator:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.trino
    container_name: trino-coordinator
    hostname: trino-coordinator
    ports:
      - "8080:8080"
      - "9080:9080"
      - "12345:12345"
    deploy:
      resources:
        limits:
          cpus: ${TRINO_COORDINATOR_CPUS}
          memory: ${TRINO_COORDINATOR_MEMORY}
    volumes:
      - "${PWD}/coordinator/config.properties:/etc/trino/config.properties"
      - "${PWD}/coordinator/jvm.config:/etc/trino/jvm.config"
      - "${PWD}/coordinator/jmx.config.yaml:/etc/trino/jmx/config.yaml"
    networks:
      trino-internal:
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/v1/status | grep '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      trino: true
      trino-worker: false
      trino-coordinator: true

  trino-worker:
    build:
      context: dockerfiles
      dockerfile: Dockerfile.trino
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: ${TRINO_WORKER_CPUS}
          memory: ${TRINO_WORKER_MEMORY}
    volumes:
      - "${PWD}/worker/config.properties:/etc/trino/config.properties"
      - "${PWD}/coordinator/jvm.config:/etc/trino/jvm.config"
      - "${PWD}/coordinator/jmx.config.yaml:/etc/trino/jmx/config.yaml"
    networks:
      trino-internal:
    expose:
      - "12345"
      - "8080"
      - "9080"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/v1/status | grep '200'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    labels:
      trino: true
      trino-worker: true
      trino-coordinator: false

  prometheus:
    user: root
    image: prom/prometheus:v2.50.0 # fix version to avoid breaking changes in future releases
    container_name: prometheus
    hostname: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - "${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus-data:/prometheus
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      trino-internal:
      monitoring:

  grafana:
    image: grafana/grafana-oss:9.5.15 # fix version to avoid breaking changes in future releases
    container_name: grafana
    hostname: grafana
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      monitoring:

networks:
  trino-internal:
    driver: bridge
  monitoring:
    driver: bridge

volumes:
  prometheus-data:
  grafana-data:
